- hosts: localhost
  become: true

  tasks: 
    - name: install apt packages
      package:
        name: "{{ item }}"
        state: present
      with_items:
        - gnome-tweaks
        - gnome-shell-extensions
        - rofi
        - htop
        - neovim
        - zsh
        - fonts-inter
        - fonts-firacode
        - fonts-ibm-plex
        - gimp
        - dconf-cli

    - name: Install JetBrains Mono font
      import_tasks: jetbrainsmono.yaml