- hosts: localhost
  become: true

  pre_tasks:
    - name: Ensure roles directory exists
      file:
        path: /etc/ansible/roles
        state: directory

    - name: Install GNOME Extensions role from GitHub
      command: ansible-galaxy install git+https://github.com/luizgavalda/gnome_extensions.git,name=luizgavalda.gnome_extensions
      args:
        creates: /etc/ansible/roles/luizgavalda.gnome_extensions

  tasks: 
    - name: install apt packages
      package:
        name: "{{ item }}"
        state: present
      with_items:
        - gnome-tweaks
        - gnome-shell-extensions
        - gnome-shell-extension-prefs
        - rofi
        - htop
        - neovim
        - zsh
        - fonts-inter
        - fonts-firacode
        - fonts-ibm-plex
        - gimp
        - dconf-cli
        - r-base
        - pandoc
        - gnome-sushi
        - s-tui
        - calibre

    - name: Install JetBrains Mono font
      import_tasks: tasks/jetbrainsmono.yaml
    
    - name: Install ZOOM
      import_tasks: tasks/zoom.yaml

    - name: Install GNOME Extensions
      import_tasks: tasks/gnome_extensions.yaml

  roles:
    - role: luizgavalda.gnome_extensions
      vars:
        gnome_extension_ids:
          - 1460
