- hosts: localhost
  become: true

  tasks: 
    - name: install apt packages
      package:
        name: "{{ item }}"
        state: present
      with_items:
        - gnome-tweaks
        - gnome-shell-extensions
        - ulauncher
        - htop
        - nvim
        - zsh
        - oh-my-zsh
        - font-inter
        - font-fira-code
        - font-jetbrains-mono
        - font-ibm-plex
        - gimp
        - dconf-cli

    - name: Install JetBrains Mono font
      import_tasks: jetbrainsmono.yaml