- hosts: localhost
  become: true

  tasks: 
    - name: install apt packages
      package:
        name: "{{ item }}"
        state: present
      with_items:
        - gnome-tweaks
        - gnome-shell-extensions
        - gnome-shell-extension-prefs
        - rofi
        - htop
        - neovim
        - zsh
        - fonts-inter
        - fonts-firacode
        - fonts-ibm-plex
        - gimp
        - dconf-cli
        - r-base
        - pandoc
        - gnome-sushi
        - s-tui
        - calibre

    - name: Install JetBrains Mono font
      import_tasks: jetbrainsmono.yaml
    
    - name: Install VSCODE
      import_tasks: vscode.yaml

    - name: Install Flatpak
      import_tasks: flatpak.yaml
    
    - name: Install ZOOM
      import_tasks: zoom.yaml

    - name: Install GNOME Extensions
      import_tasks: gnome_extensions.yaml