---
- hosts: localhost

  vars:
    user_home: "/home/{{ ansible_user }}"
    user_name: "{{ ansible_user }}"
    zsh_dependencies: []

  pre_tasks:
    - name: Ensure user directory variables are set
      set_fact:
        user_home: "/home/{{ ansible_user }}"
        user_name: "{{ ansible_user }}"

  tasks:
    - name: zsh
      import_tasks: tasks/zsh.yaml
      tags: zsh

    - name: Ensure Docker is started and enabled at boot
      systemd:
        name: docker
        state: started
        enabled: true
      tags: docker

    - name: Install APT packages
      import_tasks: tasks/apt.yaml

    - name: Install JetBrains Mono font
      import_tasks: tasks/fonts.yaml
      tags: fonts
    
    - name: Install ZOOM
      import_tasks: tasks/zoom.yaml
      
    - name: Install VSCODE
      import_tasks: tasks/vscode.yaml

    - name: Install flatpak apps
      import_tasks: tasks/flatpak.yaml
  
    - name: Install Throttled
      import_tasks: tasks/throttled.yaml
      tags: throttled

    - name: disable thermald
      import_tasks: tasks/thermald.yaml

    - name: install thinkfan
      import_tasks: tasks/thinkfan.yaml
      tags: thinkfan
    
    - name: install pyenv
      import_tasks: tasks/pyenv.yaml
      tags: python

    - name: pipx and python tools
      import_tasks: tasks/pipx.yaml
      tags: pipx

    - name: firefox configs
      import_tasks: tasks/firefox.yaml
      tags: firefox
  
    - name: MEGA
      import_tasks: tasks/mega.yaml
      tags: mega

    - name: snap
      import_tasks: tasks/snap.yaml
      tags: snap

    - name: fly
      import_tasks: tasks/fly.yaml
      tags: fly


  roles:
    - role: geerlingguy.docker
      vars:
        docker_compose_version: "latest"  # This ensures Docker Compose is installed
      tags: docker
  
  
