---
- hosts: localhost
  become: true

  tasks: 
    - name: Ensure user directory variables are set
      set_fact:
        user_home: "/home/{{ ansible_user }}"
        user_name: "{{ ansible_user }}"

    - name: Install APT packages
      import_tasks: tasks/apt.yaml

    - name: Install JetBrains Mono font
      import_tasks: tasks/jetbrainsmono.yaml
      tags: fonts
    
    - name: Install ZOOM
      import_tasks: tasks/zoom.yaml

    - name: Install flatpak apps
      import_tasks: tasks/flatpak.yaml
  
    - name: Install Throttled
      import_tasks: tasks/throttled.yaml
      tags: throttled

    - name: disable thermald
      import_tasks: tasks/thermald.yaml

    - name: install thinkfan
      import_tasks: tasks/thinkfan.yaml
      tags: thinkfan
    
    - name: install pyenv
      import_tasks: tasks/pyenv.yaml
      tags: python

    - name: cpipx and python tools
      import_tasks: tasks/pipx.yaml
      tags: dotfiles

  roles:
    - role: luizgavalda.gnome_extensions
      vars:
        gnome_extension_ids:
          - 517
          - 5410
          - 1460
