- name: Install Zoom
  hosts: localhost
  become: true
  tasks:
    - name: Download Zoom .deb package
      get_url:
        url: https://zoom.us/client/6.1.5.871/zoom_amd64.deb
        dest: /tmp/zoom_amd64.deb

    - name: Install Zoom .deb package
      apt:
        deb: /tmp/zoom_amd64.deb

    - name: Clean up downloaded .deb package
      file:
        path: /tmp/zoom_amd64.deb
        state: absent
        