- name: install apt packages
  become: true
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - gnome-tweaks
    - gnome-shell-extensions
    - gnome-shell-extension-prefs
    - rofi
    - htop
    - neovim
    - gimp
    - dconf-cli
    - r-base
    - pandoc
    - gnome-sushi
    - s-tui
    - calibre
    - qgis
    - qgis-plugin-grass
    - vlc
    - curl