- name: Ensure Firefox config-prefs.js file exists with desired settings
  blockinfile:
    path: "/etc/firefox/defaults/pref/config-prefs.js"
    create: yes
    block: |
      pref("media.ffmpeg.vaapi.enabled", true);
      pref("media.ffvpx.enabled", false);
      pref("font.name.monospace.x-western", "JetBrains Mono");
      pref("font.name.sans-serif.x-western", "Inter");
    marker: "// {mark} ANSIBLE MANAGED BLOCK"
  become: true
  become_method: sudo
