- name: Install Flatpak for Ubuntu 18.10 and later
  package:
    name: flatpak
    state: present

- name: Install Software Flatpak plugin
  package:
    name: gnome-software-plugin-flatpak
    state: present

- name: Add Flathub repository
  command: flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo

- name: Install Telegram Desktop
  command: flatpak install flathub org.telegram.desktop -y

- name: Install Spotify Client
  command: flatpak install flathub com.spotify.Client -y

- name: Install Discord
  command: flatpak install flathub com.discordapp.Discord -y

- name: Install Zotero
  command: flatpak install flathub org.zotero.Zotero -y