- name: Install Flatpak for Ubuntu 18.10 and later
  package:
    name: flatpak
    state: present

- name: Install Software Flatpak plugin
  package:
    name: gnome-software-plugin-flatpak
    state: present

- name: Add Flathub repository
  command: flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo

- name: Install Telegram Desktop
  flatpak:
    name: org.telegram.desktop
    state: present

- name: Install Spotify Client
  flatpak:
    name: com.spotify.Client
    state: present

- name: Install Discord
  flatpak:
    name: com.discordapp.Discord
    state: present

- name: Install Zotero
  flatpak:
    name: org.zotero.Zotero
    state: present