- name: Ensure user directory variables are set
  set_fact:
    user_home: "/home/{{ ansible_user }}"
    user_name: "{{ ansible_user }}"
    
- name: Check if Pyenv is installed
  become: true
  become_user: "{{ user_name }}"
  stat:
    path: "{{ user_home }}/.pyenv"
  register: pyenv_installed

- name: Install Pyenv
  become: true
  become_user: "{{ user_name }}"
  shell: curl https://pyenv.run | bash
  args:
    executable: /bin/bash
  when: not pyenv_installed.stat.exists

