- name: Download Zoom deb package
  get_url:
    url: https://zoom.us/client/latest/zoom_amd64.deb
    dest: /tmp/zoom_amd64.deb

- name: Install Zoom deb package
  apt:
    deb: /tmp/zoom_amd64.deb

- name: Clean up downloaded deb package
  file:
    path: /tmp/zoom_amd64.deb
    state: absent
    